### ISSUE TITLE
Annotation collection support?

### ISSUE THREAD

**Issue by handrews** [qri-io/jsonschema#17] opened 2018-01-19 17:36 UTC
Does this project intend to implement the optional [annotation collection](https://tools.ietf.org/html/draft-handrews-json-schema-validation-00#section-10) _[EDIT: fixed link]_ process suggested by draft-07?

The process isn't entirely nailed down in draft-07 but will be made more clear in draft-08 (hopefully with a test suite).  It will also likely be the basis for some other proposed draft-08 features.  Any feedback from an implementation attempt (or even feedback on why you'd rather not implement it) would be very helpful.

**Comment by b5** [comment] 2018-01-19 19:26
@handrews I'm guessing that link was a misfire on the copy-paste, is [this](http://json-schema.org/latest/json-schema-hypermedia.html#rfc.section.6.2.3) what you meant?

I will admit to not have had a proper chance to review the hyper-schema section of the spec, but after a quick glance the short answer should be yes. I think this repo should be a proper implementation of draft 7, which includes hyper schema 😄.

On the note of proposed features, we'll be doing a bunch of things with this library to make it work properly on [IPFS](https://ipfs.io) / the distributed web in general, which has a somewhat different take on linking. As this isn't part of the everyday use case, I'm hoping to keep this library faithful to the spec, and would happily provide feedback on shoehorning jsonschema into our admittedly-eccentric use case if would help you at all while working on draft-08.

**Comment by handrews** [comment] 2018-01-19 19:48
LOL oops, no I meant this: LOL oops no I meant this: https://tools.ietf.org/html/draft-handrews-json-schema-validation-00#section-10 (I'll edit the original).

Hyper-Schema builds on annotation collection but it's not exclusive to hyper-schema.

I would love to see a Go implementation of Hyper-Schema, although making it modular so you can choose either that or the IPFS thing (which I'd not heard of, although I hope their HTTP inefficiency complaints aren't yet another example of people reacting to HTTP/1.1 problems that HTTP/2 solves).

**Comment by handrews** [comment] 2018-01-19 19:59
@b5 is there a resource somewhere that concisely explains how the take on linking is different?  There's a lot of marketing copy on that IPFS site but I'd rather not slog through that or the 50-page white paper for this if there's something more direct.  Preferably readable rather than a video.

**Comment by b5** [comment] 2018-01-20 17:30
Ah I see, well I'm happy to report this project _already_ does support at least decoding and encoding `title`, `description`, `default`, `examples`  and `readOnly/writeOnly`, [link to source](https://github.com/qri-io/jsonschema/blob/master/schema.go#L204). I'd be happy to adjust / add a code example to show the use of these. I was very excited to see these elements included in the spec, and we'll be making heavy use of these fields in our project.

As for IPFS, the problem is not with HTTP 1.x/2.x, but with location-addressing vs. content-addressing (reffering to content by it's hash). While this is fairly deep in the documentation, [this](https://github.com/ipld/specs/tree/master/ipld#how-do-merkle-paths-work) is a good place to read about how links work on IPFS.

I'm a big fan of your suggestion of implementing hyper-schema with a BYO-resolver, allowing HTTP or IPFS link operations. Although I haven't had a chance to fully digest the spec, my initial thinking is it'd be nice if links that aren't meant to be resolved with HTTP might want to use use some other off-spec field in link description objects (for example, using some key other than `href` for links), for which it seems a separate implementation would make sense to avoid confusing package users with off-spec info.

So next steps are a proper read through on the hyper-schema spec, at which point we'll undoubtedly end up writing a library, and then on to the work of seeing how we can get it to integrate with a hypermedia protocols beyond HTTP.

Thanks for your thoughts & contributions! They're greatly appreciated.

**Comment by handrews** [comment] 2018-01-20 21:36
Thanks, @b5, this all sounds good.  I'll read up on the linking and comment further or file another issue as seems appropriate.

The intention with `href` in hyper-schema is that the scheme from the constructed URI is intended to signal how to resolve that URI.  (e.g. can this be resolved as a URL and if so how? or does the implementation have some way of using it as a URN? etc.)  I see that there are URI schemes for use with IPFS (`ipfs://` and `dweb:/ipfs/` are both mentioned in the github readme), so Hyper-Schema shouldn't need to do anything special here.

There are even a few Hyper-Schema keywords that have extensible protocol/uri-scheme-specific syntax to ensure that all protocols and URI schemes are usable even if the Hyper-Schema spec was not aware of them at the time of writing.  There've been some proposals towards tweaking those field names to be even less suggestive of HTTP.  Hyper-Schema is definitely not HTTP-specific in any way.

While the spec includes a lot of guidance on using Hyper-Schema with HTTP, that is in its own section and included as an acknowledgement of the current practical realities of dominance of HTTP and analogues such as CoAP).  Examples using other URI schemes are included in the spec (and it would be great to have more of those).

**Closed** 2019-02-18 18:19 UTC
Labels: backlog
