### ISSUE TITLE
Multiple schemas referencing each other

### ISSUE THREAD

**Issue by MaikuMori** [qri-io/jsonschema#59] opened 2020-01-15 19:34 UTC
Let's say I have a JSON Schema like:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "some.json",
    "title": "Something",
    "type": "array",
    "items": {
        "$ref": "other.json#/definitions/Other"
    }
}
```

Looking at code I know there is no logic to load references from files, but even if I manually add schemas to `DefaultSchemaPool` the code will not use it.

I have code which populates my own map of Schemas from a directory and as well adds the schema to the global pool like this:

```golang
// file = "other.json"
jsonschema.DefaultSchemaPool[file] = &rs.Schema
```

Is there any way to link multiple schemas from multiple files without editing the library code?

I noticed that there is this unfinished PR which could potentially support what I want in a way https://github.com/qri-io/jsonschema/commit/a12c30bf6b8adf00bb9c51a5b3cbd44c680a651e

Ideally I want to populate map of schemas which reference each other on application startup from a directory (not remote).

I've also been hit by this https://github.com/qri-io/jsonschema/issues/31 issue.

I don't mind writing a PR for this, just wondering if I can do something with lib in its current state.

**Comment by MaikuMori** [comment] 2020-04-25 02:14
I don't like bumping, but ...

Is this something you're looking to fix? Should I make a PR for this?

**Comment by tv42** [comment] 2020-07-28 00:03
https://github.com/qri-io/jsonschema/issues/43 seems related, this might even be a duplicate of that.

**Comment by b5** [comment] 2020-09-02 16:31
Hi @MaikuMori, so sorry for leaving this unanswered for so long. We've recently overhauled the entire package to support the latest draft of the spec, and added exactly the API you're after in the process with the `SchemaRegistry` data type. You can access and modify the package-global pool of registries with the `GetSchemaRegistry()` function. Docs here:

https://pkg.go.dev/github.com/qri-io/jsonschema?tab=doc#GetSchemaRegistry

Thanks, and apologies again for taking so long to respond.

**Closed by b5** 2020-09-02 16:31 UTC
